### ISSUE TITLE
Multiple Exceptions occur

### ISSUE THREAD

**Issue by leighayanid** [HeinrichReimer/material-singleinputform#16]
i keep getting these errors

===============================================================

FATAL EXCEPTION: main
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.heinrichreimersoftware.singleinputform.example/com.heinrichreimersoftware.singleinputform.example.MainActivity}: android.view.InflateException: Binary XML file line #84: Error inflating class android.widget.ProgressBar
                                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1970)
                                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
                                                                                                        at android.app.ActivityThread.access$600(ActivityThread.java:128)
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4517)
                                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
                                                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                                                     Caused by: android.view.InflateException: Binary XML file line #84: Error inflating class android.widget.ProgressBar
                                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
                                                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
                                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                                        at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:118)
                                                                                                        at android.app.Activity.performCreate(Activity.java:4470)
                                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
                                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
                                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995) 
                                                                                                        at android.app.ActivityThread.access$600(ActivityThread.java:128) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                        at android.os.Looper.loop(Looper.java:137) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4517) 
                                                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                        at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760) 
                                                                                                        at dalvik.system.NativeStart.main(Native Method) 
                                                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                                                        at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:586)
                                                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653) 
                                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:739) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                                        at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:118) 
                                                                                                        at android.app.Activity.performCreate(Activity.java:4470) 
                                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053) 
                                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934) 
                                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995) 
                                                                                                        at android.app.ActivityThread.access$600(ActivityThread.java:128) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                        at android.os.Looper.loop(Looper.java:137) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4517) 
                                                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                        at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760) 
                                                                                                        at dalvik.system.NativeStart.main(Native Method) 
                                                                                                     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/progress_single_input_form.xml from drawable resource ID #0x7f02004e
                                                                                                        at android.content.res.Resources.loadDrawable(Resources.java:1986)
                                                                                                        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                                                        at android.widget.ProgressBar.<init>(ProgressBar.java:255)
                                                                                                        at android.widget.ProgressBar.<init>(ProgressBar.java:239)
                                                                                                        at android.widget.ProgressBar.<init>(ProgressBar.java:235)
                                                                                                        at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:586) 
                                                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653) 
                                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:739) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                                        at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:118) 
                                                                                                        at android.app.Activity.performCreate(Activity.java:4470) 
                                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053) 
                                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934) 
                                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995) 
                                                                                                        at android.app.ActivityThread.access$600(ActivityThread.java:128) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                        at android.os.Looper.loop(Looper.java:137) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4517) 
                                                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                        at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760) 
                                                                                                        at dalvik.system.NativeStart.main(Native Method) 
                                                                                                     Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                                        at android.content.res.TypedArray.getColor(TypedArray.java:326)
                                                                                                        at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:783)
                                                                                                        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:869)
                                                                                                        at android.graphics.drawable.ScaleDrawable.inflate(ScaleDrawable.java:111)
                                                                                                        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:869)
                                                                                                        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:165)
                                                                                                        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:869)
                                                                                                        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:806)
                                                                                                    	at android.content.res.Resources.loadDrawable(Resources.jav

**Comment by HeinrichReimer** [comment]
You should read this line:
```
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
```
Basically saying that you've set a non color resource as one of singleinputform's theme colors.
[*progress_single_input_form.xml*](https://github.com/HeinrichReimer/material-singleinputform/blob/master/library/src/main/res/drawable/progress_single_input_form.xml#L27) internally uses `?attr/colorPrimary`.
Please check that your `?attr/colorPrimary` points to a valid color resource.
This is most likely not a bug with this library itself.
